#!/usr/bin/env python3
from mypi.debug.ctrl import CtrlGo
from mypi.debug.config import Config
import os.path
import subprocess
class CtrlMypiAuth(CtrlGo):
    def __init__(self):
        CtrlGo.__init__(self,service='mypi-auth')

    def run(self):
        cfg = Config()
        create_clients = False
        if not os.path.exists(cfg.filename('etc/mypi-auth/server/server_pub.pem')):
            print("creating server key...")
            args = self.get_go_run_cmdline()
            args.append("init")
            proc = subprocess.run(args=args,cwd=self.cwd)
            proc.check_returncode()
            create_clients = True
        if create_clients or not os.path.exists(cfg.filename('etc/mypi-auth/clients/mypi-router.yml')):
            print("creating mypi-router client...")
            args = self.get_go_run_cmdline()
            args.append("create-client")
            args.append("mypi-router")
            proc = subprocess.run(args=args,cwd=self.cwd)
            proc.check_returncode()

        CtrlGo.run(self)

ctrl = CtrlMypiAuth()

if __name__ == '__main__':
    ctrl.main()
