#!/bin/sh

set -x
set -e

source /mypi-setup/config

apk add wireless-tools wpa_supplicant
ip link | grep wlan0
ip link set wlan0 up
iwlist wlan0 scanning
iwconfig wlan0 essid "${WLAN_SSID}"

cat > /etc/wpa_supplicant/wpa_supplicant.conf <<-_EOF_
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
_EOF_

wpa_passphrase "${WLAN_SSID}" "${WLAN_PASSWORD}" > /etc/wpa_supplicant/wpa_supplicant.conf
wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
udhcpc -i wlan0
ip addr show wlan0

###############################################################################
#
# Update /etc/network/interfaces
#
cat >> /etc/network/interfaces <<-_EOF_

auto wlan0
iface wlan0 inet dhcp
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
_EOF_

###############################################################################
#
# Configure udhcpc to ignore DNS and GATEWAY from wlan0
#
mkdir -p /etc/udhcpc
cat > /etc/udhcpc/udhcpc.conf <<-_EOF_
NO_DNS=wlan0
NO_GATEWAY=wlan0
_EOF_

###############################################################################
#
# Enable WLAN
#
ifconfig wlan0 down
/etc/init.d/wpa_supplicant start
rc-update add wpa_supplicant boot
