#!/bin/sh

set -e

# shellcheck source=/dev/null
. /mypi-control/config

USERNAME="pi"

apk add sudo bash zsh shadow

if [ ! -f /etc/sudoers.d/wheel ]; then
    echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/wheel
fi

if ! id "${USERNAME}" >/dev/null 2> /dev/null; then
    addgroup "${USERNAME}"
    adduser -D -s "$(command -v zsh)" "${USERNAME}" -G "${USERNAME}"
fi

SSH_DIR="/home/${USERNAME}/.ssh"
SSH_AUTHORIZED_KEYS_FILE="${SSH_DIR}/authorized_keys"

if [ -n "${SSH_AUTHORIZED_KEYS}" ]; then
    mkdir -p /root/.ssh
    echo "${SSH_AUTHORIZED_KEYS}" > /root/.ssh/authorized_keys
    
    mkdir -p "/home/${USERNAME}/.ssh"
    echo "${SSH_AUTHORIZED_KEYS}" >> "${SSH_AUTHORIZED_KEYS_FILE}"
    awk '!a[$0]++' < "${SSH_AUTHORIZED_KEYS_FILE}" > "${SSH_AUTHORIZED_KEYS_FILE}.new"
    mv "${SSH_AUTHORIZED_KEYS_FILE}.new" "${SSH_AUTHORIZED_KEYS_FILE}"
    chown -R "${USERNAME}:${USERNAME}" "${SSH_DIR}"
    PASSWD="$(< /dev/urandom tr -dc A-Za-z0-9 | head -c"${1:-32}")"
    printf "%s\n%s\n" "${PASSWD}" "${PASSWD}" | passwd "${USERNAME}"
fi

mkdir -p /opt/mypi
chown "${USERNAME}:${USERNAME}" /opt/mypi
chmod 755 /opt

chsh --shell /bin/zsh "${USERNAME}"

addgroup "${USERNAME}" docker
addgroup "${USERNAME}" wheel
