#!/bin/sh

set -e

# shellcheck source=/dev/null
. /mypi-control/lib/mypi-lib

BOOT_DISK="$(find_boot_disk)"
read_partition_table "/dev/${BOOT_DISK}"

mount -o remount,rw "/media/${PARTITION_BOOT_DEVICE_NAME}"
mkdir -p /mnt

if [ "$(get_device_from_dir /mnt)" != "${PARTITION_ROOT_DEVICE}" ]; then
    # root device not yet mounted
    mount "${PARTITION_ROOT_DEVICE}" /mnt
fi

################################################################################
#
# This is what I would like to do:
#
################################################################################
#
# setup-disk -m sys /mnt
# 
# rm -f /media/${PARTITION_BOOT_DEVICE}/boot/*  
# cd /mnt       # We are in the second partition 
# rm boot/boot  # Drop the unused symbolink link
# 
# mv boot/* /media/${PARTITION_BOOT_DEVICE}/boot/
# rm -Rf boot
#
################################################################################
#
# But it doesn't work... now lets do it manually
#
################################################################################

cd /mnt

cp -a /bin /etc /home /lib /root /run /sbin /srv /usr /var .
mkdir -p .modloop
mkdir -p dev
mkdir -p media
mkdir -p proc
mkdir -p sys
mkdir -p tmp

#cp "/media/${PARTITION_BOOT_DEVICE_NAME}/boot/"* boot/

# Patch /etc/init.d/modloop to allow mounting modloop on /
# shellcheck disable=SC2016
sed 's|set --|[ "$dir" = "\/" ] \&\& dir=""; set --|' -i etc/init.d/modloop
# shellcheck disable=SC2016
sed 's| && $2 != "/"||' -i etc/init.d/modloop 
sed '/start()/s/$/\n\tmount \/media\/'"${PARTITION_BOOT_DEVICE_NAME}"'\n\tmount -o remount,rw \//' -i etc/init.d/modloop 

mkdir -p "media/${PARTITION_BOOT_DEVICE_NAME}" # It's the mount point for the first partition on the next reboot

ln -s "media/${PARTITION_BOOT_DEVICE_NAME}/boot" boot

echo "${PARTITION_BOOT_DEVICE} /media/${PARTITION_BOOT_DEVICE_NAME} vfat defaults 0 0" >> etc/fstab
if [ -n "${PARTITION_SWAP_DEVICE}" ]; then
    echo "${PARTITION_SWAP_DEVICE} none swap sw 0 0" >> etc/fstab
    mkswap "${PARTITION_SWAP_DEVICE}"
    rc-service swap start
fi

sed '/cdrom/d' -i etc/fstab   # Of course, you don't have any cdrom or floppy on the Raspberry Pi
sed '/floppy/d' -i etc/fstab

{
    echo "${PARTITION_BOOT_DEVICE} /media/${PARTITION_BOOT_DEVICE_NAME} vfat defaults 0 0"
    echo "tmpfs /var/log tmpfs defaults 0 0"
    echo "tmpfs /tmp tmpfs defaults 0 0"
} >> etc/fstab

sed '/[0-9]\/community/s/^#//' -i etc/apk/repositories   # But enable the repository for community if you want vim, mc, php, apache, nginx, etc.

cp -a /mypi-control /mnt
cp -a /etc/init.d/mypi-control /mnt/etc/init.d/
rm -f /mnt/etc/runlevels/default/mypi-control
ln -s /etc/init.d/mypi-control /mnt/etc/runlevels/default
if [ -n "${PARTITION_SWAP_DEVICE}" ]; then
    ln -s /etc/init.d/swap /mnt/etc/runlevels/boot
fi

# switch to new root filesystem
sed 's|^|root='"${PARTITION_ROOT_DEVICE}"' |' -i "/media/${PARTITION_BOOT_DEVICE_NAME}/cmdline.txt"

# todo: add 'cgroup_enable=memory' to cmdline.txt