#!/bin/sh

set -x
set -e

# shellcheck source=/dev/null
. /mypi-control/config

rc-update del hwclock boot > /dev/null 2>&1 || true
rc-update add swclock boot

apk add bash zsh htop jq docker python3 sudo git

rc-update add docker boot
service docker start

if [ -n "${WLAN_SSID}" ] && [ -n "${WLAN_PASSWORD}" ]; then
    /mypi-control/setup-wlan
fi

/mypi-control/setup-ssh

/mypi-control/setup-user
