#!/bin/sh

set -e

if [ ! -f /mypi-control/config ]; then
    echo "mypi-control is not configured... skipping"
    exit 0
fi

if [ -n "$(pgrep /mypi-control/bin/mypi-control 2>/dev/null)" ]; then
    echo "mypi-control is already running..."
    exit 0
fi

# shellcheck source=/dev/null
. /mypi-control/answer.txt

# shellcheck source=/dev/null
. /mypi-control/config

if [ "$(hostname)" = "localhost" ]; then
    # shellcheck disable=SC2086
    /sbin/setup-hostname ${HOSTNAMEOPTS}
    /etc/init.d/hostname --quiet restart
fi

if [ -z "$(ifconfig)" ]; then
    # there is no network configured yet... lets do it
    echo "${INTERFACESOPTS}" | /sbin/setup-interfaces -i
    # start networking...
    /etc/init.d/networking --quiet start >/dev/null

    # ensure that the time is not to far in the past
    date -s "@$(date -r /mypi-control/config "+%s")"

    # but lets try to use NTP to get the correct time
    # shellcheck disable=SC2086
    /sbin/setup-ntp ${NTPOPTS}
fi

if [ -f /mypi-control/bin/mypi-control ]; then
    /mypi-control/bin/mypi-control &
fi

# if [ ! -f /tmp/setup-alpine.txt ]; then
#     (
#         echo ---- starting setup-alpine ----
#         echo
#         NOCOMMIT=1 setup-alpine -f /mypi-control/answer.txt
#         echo
#         echo ---- finished setup-alpine ----
#     ) > /tmp/setup-alpine.txt 2>&1
# fi

exit 0

#cd "/media/${BOOT_DEVICE_NAME}"

# NOCOMMIT=1 setup-alpine -f /mypi-control/answer.txt
# 
# apk update
# apk add e2fsprogs
# 
# yes | mkfs.ext4 "/dev/${ROOT_DEVICE_NAME}"
# 
# mount "/dev/${ROOT_DEVICE_NAME}" /mnt
# 
# /mypi-control/setup-disk
# 
# cd /mnt
# 
# mkdir "media/${BOOT_DEVICE_NAME}" # It's the mount point for the first partition on the next reboot
# 
# ln -s "media/${BOOT_DEVICE_NAME}/boot" boot
# 
# echo "/dev/${BOOT_DEVICE_NAME} /media/${BOOT_DEVICE_NAME} vfat defaults 0 0" >> etc/fstab
# if [ -n "${SWAP_DEVICE_NAME}" ]; then
#     echo "/dev/${SWAP_DEVICE_NAME} none swap sw 0 0" >> etc/fstab
#     rc-service swap start
# fi
# 
# sed -i '/cdrom/d' etc/fstab   # Of course, you don't have any cdrom or floppy on the Raspberry Pi
# sed -i '/floppy/d' etc/fstab
# 
# sed -i '/v[0-9][0-9.]*[0-9]\/community/s/^#//' /mnt/etc/apk/repositories   # But enable the repository for community if you want vim, mc, php, apache, nginx, etc.
# 
# cp -a /mypi-control /mnt
# mv /mnt/mypi-control/setup-phase-2 /mnt/mypi-control/setup
# cp -a /etc/init.d/mypi-control /mnt/etc/init.d/
# cp -a /etc/runlevels/default/mypi-control /mnt//etc/runlevels/default
# 
# # switch to new root filesystem
# sed -i "s/^/root=\/dev\/${ROOT_DEVICE_NAME} /" "/media/${BOOT_DEVICE_NAME}/cmdline.txt"  
# reboot 
