#!/bin/sh

apk add busybox-static apk-tools-static

#sed -i -e 's/v3\.13/v3.14/g' /etc/apk/repositories

if ! apk.static upgrade --no-self-upgrade --available --simulate; then
    echo "upgrade simulation failed"
    exit 1
fi

apk.static upgrade --no-self-upgrade --available

# /etc/alpine-release: 3.13.0
# Linux mypi 5.10.7-0-rpi4 #1-Alpine SMP PREEMPT Thu Jan 14 07:55:06 UTC 2021 aarch64 Linux

ALPINE_RELEASE="$(cat /etc/alpine-release)"

KERNEL_RELEASE="$(uname -r)"
KERNEL_VARIANT="$(echo "${KERNEL_RELEASE}" | sed 's/.*-//')"

NEW_KERNEL_RELEASE="$(cat /usr/share/kernel/rpi4/kernel.release)"

CCU_MODULE_DIR="/lib/modules/${NEW_KERNEL_RELEASE}/kernel/ccu"

if [ ! -d "${CCU_MODULE_DIR}" ]; then

    CMD="$(cat <<__EOF__
set -e
apk add linux-${KERNEL_VARIANT} linux-${KERNEL_VARIANT}-dev alpine-sdk
mkdir -p /build
cd /build
git clone https://github.com/alexreinert/piVCCU.git
cd piVCCU/kernel
make
mkdir "${CCU_MODULE_DIR}"
cp *.ko "${CCU_MODULE_DIR}/"
depmod "${NEW_KERNEL_RELEASE}"
__EOF__
)"

    docker run -v /lib/modules:/lib/modules "alpine:${ALPINE_RELEASE}" sh -c "${CMD}"
fi