#!/usr/bin/env python3

import shutil
import os

from lib import golang

root_dir = os.path.dirname(os.path.dirname(__file__))
build_dir = os.path.join(root_dir,"build")
mypi_setup_dist_dir = os.path.join(build_dir,"mypi-setup")

if not os.path.exists(os.path.join(mypi_setup_dist_dir,"mypi-control")):
    os.makedirs(os.path.join(mypi_setup_dist_dir,"mypi-control"))

golang.build("mypi-control", goos="linux", goarch="aarch64")

golang.build("mypi-setup", goos="linux", goarch="aarch64")
golang.build("mypi-setup", goos="linux", goarch="amd64")
golang.build("mypi-setup", goos="darwin", goarch="aarch64")
golang.build("mypi-setup", goos="darwin", goarch="amd64")
golang.build("mypi-setup", goos="windows", goarch="amd64")

shutil.copy(os.path.join(build_dir,"linux-aarch64/mypi-control"),os.path.join(mypi_setup_dist_dir,"mypi-control/mypi-control-linux-arm64"))