#!/usr/bin/env python3

from python_path import PythonPath

with PythonPath("lib",relative_to=__file__):
    import golang

golang.build("mypi-setup", goos="linux", goarch="aarch64")
golang.build("mypi-setup", goos="linux", goarch="amd64")
golang.build("mypi-setup", goos="darwin", goarch="aarch64")
golang.build("mypi-setup", goos="darwin", goarch="amd64")
golang.build("mypi-setup", goos="windows", goarch="amd64")