#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

cd "${DIR_ROOT}"
GOOS=linux GOARCH=arm64 go build -o "${DIR_ROOT}/build/mypi-debug-proxy" "cmd/mypi-debug-proxy/"*.go

(cd build; tar czf /dev/stdout mypi-debug-proxy) | \
ssh pi@mypi -p 2022 \
    -o ServerAliveInterval=60 \
    -o ServerAliveCountMax=3 \
    -R 8081:localhost:8080 \
bash -c \
'"
tar xvzf /dev/stdin
pwd
cd /home/pi
ps -ef | grep mypi-debug-proxy | grep -v grep | sed \"s/  */ /g\" | cut -d\" \" -f 2 | xargs -r -n 1 kill -9
/home/pi/mypi-debug-proxy
"'
