#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

SESSION_NAME=mypi-tools-debug
tmux kill-session -t "${SESSION_NAME}" &> /dev/null || true
tmux new-session -d -s "${SESSION_NAME}" -n tmp
if [[ -d "${DIR_ROOT}/../mypi-admin" ]]; then
    tmux split-window -v -t "${SESSION_NAME}:0.0"
    tmux send-keys -t "${SESSION_NAME}:0.1" "cd \"${DIR_ROOT}/../mypi-admin\"; PORT=9100 npm run dev-remote" C-m
    tmux resize-pane -t "${SESSION_NAME}:0.0" -y 3
fi
tmux send-keys -t "${SESSION_NAME}:0.0" "ssh -R 8080:127.0.0.1:8080 -L 11111:localhost:11111 pi@rpi.fritz.box /opt/mypi/scripts/debug" C-m
tmux resize-pane -t "${SESSION_NAME}:0.0" -y 3

