name: Build & Test
on: [push]
jobs:

  build:
    name: "Build (golang)"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out sources
      uses: actions/checkout@v3

    - name: Build
      run: |
        ./scripts/test-golang

    - name: Upload coverage results
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build-js:
    name: "Build (JS)"
    runs-on: ubuntu-latest
    steps:

    - name: Check out sources
      uses: actions/checkout@v3

    - name: Build
      run: 
        ./scripts/test-web
