name: Build & Test
on: [push]
jobs:

  build:
    name: "Build (golang)"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
      id: go

    - name: Check out sources
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Prepare Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - run: ./scripts/prepare

    - name: Build
      run: |
        ./scripts/test-golang

    - name: Upload coverage results
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build-js:
    name: "Build (JS)"
    runs-on: ubuntu-latest
    steps:

    - name: Check out sources
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Build
      run: 
        ./scripts/test-web
