name: Build & Test
on:  
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
jobs:

  build:
    name: "Build (golang)"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
      id: go

    - name: Check out sources
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - name: Prepare Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - run: ./scripts/prepare

    - name: Build
      run: |
        ./scripts/test-golang

    - name: Upload coverage results
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: v1.55.2


  build-js:
    name: "Build (JS)"
    runs-on: ubuntu-latest
    steps:

    - name: Check out sources
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - name: Build
      run: 
        ./scripts/test-web
